name: RedUtils
version: 0.0.6
author: alan20210202
main: me.alan20210202.redutils.RedUtils
api-version: 1.13

commands:
  redutils:
    description: The central command for RedUtils
  ru:
    description: Redutils command for short
  redutilsas:
    description: The central command to use RedUtils in Command Blocks
  ruas:
    description: Redutilsas command for short